---
title: "Introduction to ebm"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Introduction to ebm}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
self_contained: false
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  echo = TRUE,
  cache = FALSE,
  fig.width = 6,
  fig.asp = 0.618,
  out.width = "70%"
)
```

**WARNING**: This vignette is very much a work in progress and is subject to change as the package evolves!


## Getting started

This package requires [reticulate](https://rstudio.github.io/reticulate/) and an appropriate Python environment with the [interpret](https://github.com/interpretml/interpret/) library installed. If you're not a Python user, then I'd suggest reading through some of the **reticulate** vignettes to learn more. In particular:

* See `vignette("versions", package = "reticulate")` for learning more about Python version configuration.
* See `vignette("python_packages", package = "reticulate")` for learning more about installing Python packages.
* See `vignette("python_primer", package = "reticulate")` for learning more about interacting with Python objects through reticulate (this can be useful for understanding more advanced usage of the **ebm** package)

For simplicity, this package also provides an `install_interpret()` function for installing the sole Python library dependency; see `ebm::?install_interpret()` for details.

For a full overview of the **ebm** package, see article titled "RJournal article (in progress)".
